# Generated by Django 4.2.13 on 2024-05-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesharing',
            name='values',
            field=models.JSONField(default=list),
        ),
    ]
