# Generated by Django 5.0.6 on 2024-05-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("splitApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensesharing",
            name="total_shares",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
