# Generated by Django 5.0.6 on 2024-05-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("splitApp", "0002_alter_expensesharing_total_shares"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensesharing",
            name="values",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
